scrumptious/urls.py
from django.contrib.auth import views as auth_views
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.views.generic.base import RedirectView


urlpatterns = [
    path("admin/", admin.site.urls),
    path("recipes/", include("recipes.urls")),
    path("meal_plans/", include("meal_plans.urls")),
    path("tags/", include("tags.urls")),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("recipes_list")),
        name="home",
    ),
    path("accounts/login/", auth_views.LoginView.as_view(), name="login"),
    path("accounts/logout/", auth_views.LogoutView.as_view(), name="logout"),
]

tags/urls.py
from django.urls import path
from tags.models import Tag

from tags.views import (
    TagCreateView,
    TagDeleteView,
    TagDetailView,
    TagListView,
    TagUpdateView
)

urlpatterns = [
    path("", TagListView.as_view(), name="tags_list"),
    path("<int:pk>/", TagDetailView.as_view(), name="tags_detail"),
    path("<int:pk>/delete/", TagDeleteView.as_view(), name="tags_delete"),
    path("new/", TagCreateView.as_view(), name="tags_new"),
    path("<int:pk>/edit/", TagUpdateView.as_view(), name="tags_edit"),
]

tags/models.py
from django.conf import settings
from django.db import models
from recipes.models import Recipe

USER_MODEL = settings.AUTH_USER_MODEL
# Create your models here.

class Tag(models.Model):
    name = models.CharField(max_length = 20)
    author = models.ForeignKey(
        USER_MODEL,
        related_name="tags",
        on_delete=models.CASCADE,
        null=True
    )
    recipes = models.ManyToManyField(
        Recipe, related_name = "tags",
    )

    def __str__(self):
        return str(self.name)

tags/forms.py
from django import forms

from tags.models import Tag

class TagForm(forms.ModelForm):
    class Meta:
        model = Tag
        fields = ["name", "author"]

tags/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView

from tags.models import Tag
from tags.forms import TagForm


# Create your views here.
# def show_tags(request):
#     context = {
#         "tags": Tag.objects.all() if Tag else None,
#     }
#     return render(request, "tags/list.html", context)


class TagListView(ListView):
    model = Tag
    template_name = "tags/list.html"


class TagDetailView(DetailView):
    model = Tag
    template_name = "tags/detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class TagCreateView(LoginRequiredMixin, CreateView):
    model = Tag
    template_name = "tags/new.html"
    fields = ["name", "author"]
    success_url = reverse_lazy("tags_list")


class TagUpdateView(LoginRequiredMixin, UpdateView):
    model = Tag
    template_name = "tags/edit.html"
    fields = ["name", "author"]
    success_url = reverse_lazy("tags_list")


class TagDeleteView(LoginRequiredMixin, DeleteView):
    model = Tag
    template_new = "tags/delete.html"
    success_url = reverse_lazy("tags_list")

tags/templates/tags/delete.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit {{ recipe.name }} - Scrumptious</title>
    <link rel="stylesheet" href="{% static 'css/app.css' %}">
</head>

<body>
    <header>
        <nav>
            <ul>
                <li>
                    <a href="{% url 'home' %}">Scrumptious</a>
                </li>
                <li>
                    <a href="{% url 'admin:index' %}">Admin</a>
                </li>
                <li>
                    <a href="{% url 'recipe_new' %}">Write a recipe</a>
                </li>
            </ul>
        </nav>
    </header>
    <main class="recipe-form">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="control">
                <button class="button">Delete</button>
            </div>
        </form>
    </main>
</body>

</html>

tags/templates/tags/detail.html
{% load static %}
{% load markdownify %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>New Recipe - Scrumptious</title>
    <link rel="stylesheet" href="{% static 'css/app.css' %}">
</head>

<body>
    <header>
        <nav>
            <ul>
                <li>
                    <a href="{% url 'home' %}">Scrumptious</a>
                </li>
                <li>
                    <a href="{% url 'admin:index' %}">Admin</a>
                </li>
                <li>
                    <a href="{% url 'recipe_new' %}">Write a recipe</a>
                </li>
            </ul>
        </nav>
    </header>
    <main class="recipe-detail">
        <div>
            <a href="{% url 'recipe_edit' recipe.id %}">Edit</a>
            <a href="{% url 'recipe_delete' recipe.id %}">Delete</a>
        </div>
        {% if recipe.image %}
        <img src="{{ recipe.image }}" class="pull-right">
        {% endif %}
        <h1>{{ recipe.name }}</h1>
        <p>
            Created on {{ recipe.created }} |
            Updated on {{ recipe.updated }}
        </p>
        <form method="post" action="{% url 'recipe_rating' recipe.id %}">
            {% csrf_token %}
            {{ rating_form.as_p }}
            <button class="button">Rate</button>
        </form>
        <p>Tags: {% for tag in recipe.tags.all %}{{ tag.name }} {% endfor %}</p>
        <p>{{ recipe.description | markdownify }}</p>
        <h2>Ingredients</h2>
        <table>
            <thead>
                <tr>
                    <th colspan="2">Amount</th>
                    <th>Food item</th>
                </tr>
            </thead>
            <tbody>
                {% for ingredient in recipe.ingredients.all %}
                <tr>
                    <td>{{ ingredient.amount }}</td>
                    <td>{{ ingredient.measure.name }}</td>
                    <td>{{ ingredient.food.name }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <h2>Steps</h2>
        <ol>
            {% for step in recipe.steps.all %}
            <li>{{ step.directions }}</li>
            {% endfor %}
        </ol>
    </main>
</body>

</html>

tags/templates/tags/edit.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit {{ recipe.name }} - Scrumptious</title>
    <link rel="stylesheet" href="{% static 'css/app.css' %}">
</head>

<body>
    <header>
        <nav>
            <ul>
                <li>
                    <a href="{% url 'home' %}">Scrumptious</a>
                </li>
                <li>
                    <a href="{% url 'admin:index' %}">Admin</a>
                </li>
                <li>
                    <a href="{% url 'recipe_new' %}">Write a recipe</a>
                </li>
            </ul>
        </nav>
    </header>
    <main class="recipe-form">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="control">
                <button class="button">Update</button>
            </div>
        </form>
    </main>
</body>

</html>

tags/templates/tags/list.html
{% extends 'base.html' %}


{% block pagination %}
<div class="pagination">
  <span class="step-links">
    {% if page_obj.has_previous %}
    <a href="?page=1">&laquo; first</a>
    <a href="?page={{ page_obj.previous_page_number }}">previous</a>
    {% endif %}

    <span class="current">
      Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
    </span>

    {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}">next</a>
    <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
    {% endif %}
  </span>
</div>
{% endblock pagination %}


{% block content %}
<main class="recipe-grid">
  {% for tag in tag_list %}
  <div class="recipe-card">
    <h2 class="recipe-card-title">
      <a href="{% url 'tag_detail' tag.id %}">{{ tag.name }}</a>
    </h2>
    {% for recipe in tag.recipes.all %}
    <p>
      <a href="{% url 'recipe_detail' recipe.pk %}">{{ recipe.name }}</a>
    </p>
    {% endfor %}
  </div>
  {% empty %}
  <div>
    <h1>No tags, yet</h1>
    <p>
      Would you like to
      <a href="{% url 'tag_new' %}">create</a>
      one?
    </p>
  </div>
  {% endfor %}
</main>
{% endblock content %}

tags/templates/tags/new.html
{% extends 'base.html' %}


<main class="recipe-form">
    <form method="get">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="control">
            <button class="button">Create</button>
        </div>
    </form>
    <div>
        <h1>No tags, yet</h1>
        <p>
            Would you like to
            <a href="{% url 'tag_new' %}">create</a>
            one?
        </p>
    </div>
</main>