meal_plans/urls.py
from django.urls import path

from meal_plans.views import (
    MealPlanCreateView,
    MealPlanUpdateView,
    MealPlanDeleteView,
    MealPlanDetailView,
    MealPlanListView,
    log_rating,
)


urlpatterns = [
    path("meal_plans/", MealPlanListView.as_view(), name="meal_plans_list"),
    path(
        "meal_plans/<int:pk>/",
        MealPlanDetailView.as_view(),
        name="meal_plans_detail",
    ),
    path(
        "meal_plans/create/",
        MealPlanCreateView.as_view(),
        name="meal_plans_new",
    ),
    path(
        "meal_plans/<int:pk>/edit/",
        MealPlanUpdateView.as_view(),
        name="meal_plans_edit",
    ),
    path(
        "meal_plans/<int:pk>/delete/",
        MealPlanDeleteView.as_view(),
        name="meal_plans_delete",
    ),
    path("<int:mealplan_id>/ratings/", log_rating, name="meal_plans_rating"),
]

scrumptious/urls.py
from django.contrib.auth import views as auth_views
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.views.generic.base import RedirectView


urlpatterns = [
    path("admin/", admin.site.urls),
    path("recipes/", include("recipes.urls")),
    path("meal_plans/", include("meal_plans.urls")),
    path("tags/", include("tags.urls")),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("recipes_list")),
        name="home",
    ),
    path("accounts/login/", auth_views.LoginView.as_view(), name="login"),
    path("accounts/logout/", auth_views.LogoutView.as_view(), name="logout"),
]

tags/urls.py
from django.urls import path
from tags.models import Tag

from tags.views import (
    TagCreateView,
    TagDeleteView,
    TagDetailView,
    TagListView,
    TagUpdateView
)

urlpatterns = [
    path("", TagListView.as_view(), name="tags_list"),
    path("<int:pk>/", TagDetailView.as_view(), name="tags_detail"),
    path("<int:pk>/delete/", TagDeleteView.as_view(), name="tags_delete"),
    path("new/", TagCreateView.as_view(), name="tags_new"),
    path("<int:pk>/edit/", TagUpdateView.as_view(), name="tags_edit"),
]

meal_plans/models.py
from django.conf import settings
from django.db import models
from django.forms import CharField, DateField
from django.core.validators import MaxValueValidator, MinValueValidator

from recipes.models import Recipe

from recipes.models import USER_MODEL

USER_MODEL = settings.AUTH_USER_MODEL

# Create your models here.


class MealPlan(models.Model):
    name = models.CharField(max_length=120)
    created = models.DateField(auto_now_add=True)
    updated = models.DateField(auto_now_add=True)
    owner = models.ForeignKey(USER_MODEL, on_delete=models.CASCADE, null=True)
    recipes = models.ManyToManyField("recipes.Recipe", related_name="recipes")

    def __str__(self):
        return str(self.name)


class Rating(models.Model):
    value = models.PositiveSmallIntegerField(
        validators=[
            MaxValueValidator(5),
            MinValueValidator(1),
        ]
    )
    mealplan = models.ForeignKey(
        "MealPlan",
        related_name="ratings",
        on_delete=models.CASCADE,
    )

meal_plans/forms.py
from django import forms

from meal_plans.models import MealPlan, Rating


class MealPlanForm(forms.ModelForm):
    class Meta:
        model = MealPlan
        fields = [
            "name",
        ]


class RatingForm(forms.ModelForm):
    class Meta:
        model = Rating
        fields = ["value"]

meal_plans/views.py
from re import template
from black import format_cell
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView, CreateView, DeleteView
from django.views.generic.list import ListView
from meal_plans.models import MealPlan
from meal_plans.forms import RatingForm

# Create your views here.


def log_rating(request, mealplan_id):
    try:
        if request.method == "POST":
            form = RatingForm(request.POST)
            if form.is_valid():
                rating = form.save(commit=False)
                rating.mealplan = MealPlan.objects.get(pk=mealplan_id)
                rating.save()
        return redirect("meal_plans_detail", pk=mealplan_id)

    except MealPlan.DoesNotExist:
        return redirect("meal_plans_list")


class MealPlanListView(LoginRequiredMixin, ListView):
    model = MealPlan
    template_name = "meal_plans/list.html"
    paginate_by = 2

    def get_queryset(self):
        return MealPlan.objects.filter(owner=self.request.user)


class MealPlanCreateView(LoginRequiredMixin, CreateView):
    model = MealPlan
    template_name = "meal_plans/new.html"
    fields = ["name"]
    success_url = reverse_lazy("meal_plans_list")

    def form_valid(self, form):
        plan = form.save(commit=False)
        plan.owner = self.request.user
        plan.save()
        form.save_m2m()
        return redirect("meal_plans_detail", pk=plan.id)

    def get_queryset(self):
        return MealPlan.objects.filter(owner=self.request.user)


class MealPlanDetailView(LoginRequiredMixin, DetailView):
    model = MealPlan
    template_name = "meal_plans/detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["rating_form"] = RatingForm()
        return context

    def get_queryset(self):
        return MealPlan.objects.filter(owner=self.request.user)


class MealPlanUpdateView(LoginRequiredMixin, UpdateView):
    model = MealPlan
    template_name = "meal_plans/edit.html"
    fields = ["name"]
    success_url = reverse_lazy("meal_plans_list")

    def get_queryset(self):
        return MealPlan.objects.filter(owner=self.request.user)


class MealPlanDeleteView(LoginRequiredMixin, DeleteView):
    model = MealPlan
    template_name = "meal_plans/delete.html"
    success_url = reverse_lazy("meal_plans_list")

    def get_queryset(self):
        return MealPlan.objects.filter(owner=self.request.user)

meal_plans/templates/meal_plans/delete.html
{% extends 'base.html' %}

{% block content %}
<main class="recipe-form">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="control">
            <button class="button">Delete</button>
        </div>
    </form>
</main>
{% endblock content %}

meal_plans/templates/meal_plans/detail.html
{% extends 'base.html' %}
{% load markdownify %}

{% block content %}
<main class="recipe-detail">
    <div>
        <a href="{% url 'meal_plans_edit' mealplan.id %}">Edit</a>
        <a href="{% url 'meal_plans_delete' mealplan.id %}">Delete</a>
    </div>
    {% if recipe.image %}
    <img src="{{ recipe.image }}" class="pull-right">
    {% endif %}
    <h1>{{ mealplan.name }}</h1>
    <h2>by: {{ mealplan.owner | default_if_none:"Unknown" }}</h2>
    <p>
        Created on {{ mealplan.created }} |
        Updated on {{ mealplan.updated }}
    </p>
    <form method="post" action="{% url 'meal_plans_rating' mealplan.id %}">
        {% csrf_token %}
        {{ rating_form.as_p }}
        <button class="button">Rate</button>
    </form>
    <p>Tags: {% for tag in recipe.tags.all %}{{ tag.name }} {% endfor %}</p>
    <p>{{ recipe.description | markdownify }}</p>
    <h2>Ingredients</h2>
    <table>
        <thead>
            <tr>
                <th colspan="2">Amount</th>
                <th>Food item</th>
            </tr>
        </thead>
        <tbody>
            {% for ingredient in recipe.ingredients.all %}
            <tr>
                <td>{{ ingredient.amount }}</td>
                <td>{{ ingredient.measure.name }}</td>
                <td>{{ ingredient.food.name }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <h2>Steps</h2>
    <ol>
        {% for step in recipe.steps.all %}
        <li>{{ step.directions }}</li>
        {% endfor %}
    </ol>
</main>
{% endblock content %}

meal_plans/templates/meal_plans/edit.html
{% extends 'base.html' %}

{% block content %}
<main class="recipe-form">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="control">
            <button class="button">Update</button>
        </div>
    </form>
</main>
{% endblock content %}

meal_plans/templates/meal_plans/list.html
{% extends 'base.html' %}


{% block content %}
<main class="recipe-form">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="control">
            <a href="{% url 'meal_plans_new' %}">Create</a>
        </div>
    </form>
</main>
<p></p>
<main class="recipe-grid">
    {% for mealplan in mealplan_list %}
    <div class="recipe-card">
        <h2 class="recipe-card-title">
            <a href="{% url 'meal_plans_detail' mealplan.pk %}">{{ mealplan.name }}</a>
        </h2>
        {% for recipe in mealplan.recipes.all %}
        <p>
            <a href="{% url 'recipe_detail' recipe.pk %}">{{ recipe.name }}</a>
        </p>
        {% endfor %}
        <p class="recipe-card-date">{{ MealPlan.updated }}</p>
    </div>
    {% empty %}
    <div>
        <h1>No meals planned yet.</h1>
        <p>
            Want to
            <a href="{% url 'meal_plans_new' %}">add</a>
            a new one?
        </p>
    </div>
    {% endfor %}
</main>
{% endblock content %}

meal_plans/templates/meal_plans/new.html
{% extends 'base.html' %}


{% block content %}
<main class="recipe-form">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="control">
            <button class="button">Create</button>
        </div>
    </form>
</main>
{% endblock content %}